cmake_minimum_required(VERSION 3.0)
#[[
/*
 * Sailfin: a Jellyfin client written using Qt
 * Copyright (C) 2021 Chris Josten and the Sailfin Contributors.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */
/*
 * WARNING: THIS IS AN AUTOMATICALLY GENERATED FILE! PLEASE DO NOT EDIT THIS, AS YOUR EDITS WILL GET
 * OVERWRITTEN AT SOME POINT! 
 *
 * If there is a bug in this file, please fix the code generator used to generate this file found in
 * core/openapigenerator.d. 
 *
 * This file is generated based on Jellyfin's OpenAPI description, "openapi.json". Please update that
 * file with a newer file if needed instead of manually updating the files.
 */

]]
set(openapi_HEADERS
	./include/JellyfinQt/dto/loglevel.h
	./include/JellyfinQt/dto/activitylogentry.h
	./include/JellyfinQt/dto/activitylogentryqueryresult.h
	./include/JellyfinQt/dto/authenticationinfo.h
	./include/JellyfinQt/dto/authenticationinfoqueryresult.h
	./include/JellyfinQt/dto/itemfields.h
	./include/JellyfinQt/dto/itemfilter.h
	./include/JellyfinQt/dto/imagetype.h
	./include/JellyfinQt/dto/video3dformat.h
	./include/JellyfinQt/dto/externalurl.h
	./include/JellyfinQt/dto/mediaprotocol.h
	./include/JellyfinQt/dto/mediasourcetype.h
	./include/JellyfinQt/dto/videotype.h
	./include/JellyfinQt/dto/isotype.h
	./include/JellyfinQt/dto/mediastreamtype.h
	./include/JellyfinQt/dto/subtitledeliverymethod.h
	./include/JellyfinQt/dto/mediastream.h
	./include/JellyfinQt/dto/mediaattachment.h
	./include/JellyfinQt/dto/transportstreamtimestamp.h
	./include/JellyfinQt/dto/mediasourceinfo.h
	./include/JellyfinQt/dto/playaccess.h
	./include/JellyfinQt/dto/mediaurl.h
	./include/JellyfinQt/dto/baseitemperson.h
	./include/JellyfinQt/dto/nameguidpair.h
	./include/JellyfinQt/dto/useritemdatadto.h
	./include/JellyfinQt/dto/dayofweek.h
	./include/JellyfinQt/dto/chapterinfo.h
	./include/JellyfinQt/dto/locationtype.h
	./include/JellyfinQt/dto/metadatafield.h
	./include/JellyfinQt/dto/imageorientation.h
	./include/JellyfinQt/dto/channeltype.h
	./include/JellyfinQt/dto/programaudio.h
	./include/JellyfinQt/dto/baseitemdto.h
	./include/JellyfinQt/dto/baseitemdtoqueryresult.h
	./include/JellyfinQt/dto/encodingcontext.h
	./include/JellyfinQt/dto/brandingoptions.h
	./include/JellyfinQt/dto/channelmediatype.h
	./include/JellyfinQt/dto/channelmediacontenttype.h
	./include/JellyfinQt/dto/channelitemsortfield.h
	./include/JellyfinQt/dto/channelfeatures.h
	./include/JellyfinQt/dto/collectioncreationresult.h
	./include/JellyfinQt/dto/version.h
	./include/JellyfinQt/dto/imagesavingconvention.h
	./include/JellyfinQt/dto/metadataoptions.h
	./include/JellyfinQt/dto/namevaluepair.h
	./include/JellyfinQt/dto/repositoryinfo.h
	./include/JellyfinQt/dto/pathsubstitution.h
	./include/JellyfinQt/dto/serverconfiguration.h
	./include/JellyfinQt/dto/mediaencoderpathdto.h
	./include/JellyfinQt/dto/problemdetails.h
	./include/JellyfinQt/dto/configurationpagetype.h
	./include/JellyfinQt/dto/configurationpageinfo.h
	./include/JellyfinQt/dto/generalcommandtype.h
	./include/JellyfinQt/dto/headermatchtype.h
	./include/JellyfinQt/dto/httpheaderinfo.h
	./include/JellyfinQt/dto/deviceidentification.h
	./include/JellyfinQt/dto/xmlattribute.h
	./include/JellyfinQt/dto/dlnaprofiletype.h
	./include/JellyfinQt/dto/directplayprofile.h
	./include/JellyfinQt/dto/transcodeseekinfo.h
	./include/JellyfinQt/dto/transcodingprofile.h
	./include/JellyfinQt/dto/profileconditiontype.h
	./include/JellyfinQt/dto/profileconditionvalue.h
	./include/JellyfinQt/dto/profilecondition.h
	./include/JellyfinQt/dto/containerprofile.h
	./include/JellyfinQt/dto/codectype.h
	./include/JellyfinQt/dto/codecprofile.h
	./include/JellyfinQt/dto/responseprofile.h
	./include/JellyfinQt/dto/subtitleprofile.h
	./include/JellyfinQt/dto/deviceprofile.h
	./include/JellyfinQt/dto/clientcapabilities.h
	./include/JellyfinQt/dto/deviceinfo.h
	./include/JellyfinQt/dto/deviceinfoqueryresult.h
	./include/JellyfinQt/dto/deviceoptions.h
	./include/JellyfinQt/dto/scrolldirection.h
	./include/JellyfinQt/dto/sortorder.h
	./include/JellyfinQt/dto/displaypreferencesdto.h
	./include/JellyfinQt/dto/deviceprofiletype.h
	./include/JellyfinQt/dto/deviceprofileinfo.h
	./include/JellyfinQt/dto/controlresponse.h
	./include/JellyfinQt/dto/defaultdirectorybrowserinfodto.h
	./include/JellyfinQt/dto/filesystementrytype.h
	./include/JellyfinQt/dto/filesystementryinfo.h
	./include/JellyfinQt/dto/validatepathdto.h
	./include/JellyfinQt/dto/queryfilterslegacy.h
	./include/JellyfinQt/dto/queryfilters.h
	./include/JellyfinQt/dto/imageformat.h
	./include/JellyfinQt/dto/imageinfo.h
	./include/JellyfinQt/dto/imagebynameinfo.h
	./include/JellyfinQt/dto/externalidmediatype.h
	./include/JellyfinQt/dto/externalidinfo.h
	./include/JellyfinQt/dto/remotesearchresult.h
	./include/JellyfinQt/dto/bookinfo.h
	./include/JellyfinQt/dto/bookinforemotesearchquery.h
	./include/JellyfinQt/dto/boxsetinfo.h
	./include/JellyfinQt/dto/boxsetinforemotesearchquery.h
	./include/JellyfinQt/dto/movieinfo.h
	./include/JellyfinQt/dto/movieinforemotesearchquery.h
	./include/JellyfinQt/dto/songinfo.h
	./include/JellyfinQt/dto/albuminfo.h
	./include/JellyfinQt/dto/albuminforemotesearchquery.h
	./include/JellyfinQt/dto/artistinfo.h
	./include/JellyfinQt/dto/artistinforemotesearchquery.h
	./include/JellyfinQt/dto/musicvideoinfo.h
	./include/JellyfinQt/dto/musicvideoinforemotesearchquery.h
	./include/JellyfinQt/dto/personlookupinfo.h
	./include/JellyfinQt/dto/personlookupinforemotesearchquery.h
	./include/JellyfinQt/dto/seriesinfo.h
	./include/JellyfinQt/dto/seriesinforemotesearchquery.h
	./include/JellyfinQt/dto/trailerinfo.h
	./include/JellyfinQt/dto/trailerinforemotesearchquery.h
	./include/JellyfinQt/dto/metadatarefreshmode.h
	./include/JellyfinQt/dto/seriesstatus.h
	./include/JellyfinQt/dto/parentalrating.h
	./include/JellyfinQt/dto/countryinfo.h
	./include/JellyfinQt/dto/culturedto.h
	./include/JellyfinQt/dto/metadataeditorinfo.h
	./include/JellyfinQt/dto/thememediaresult.h
	./include/JellyfinQt/dto/allthememediaresult.h
	./include/JellyfinQt/dto/itemcounts.h
	./include/JellyfinQt/dto/libraryoptioninfodto.h
	./include/JellyfinQt/dto/imageoption.h
	./include/JellyfinQt/dto/librarytypeoptionsdto.h
	./include/JellyfinQt/dto/libraryoptionsresultdto.h
	./include/JellyfinQt/dto/mediaupdateinfodto.h
	./include/JellyfinQt/dto/mediapathinfo.h
	./include/JellyfinQt/dto/typeoptions.h
	./include/JellyfinQt/dto/libraryoptions.h
	./include/JellyfinQt/dto/virtualfolderinfo.h
	./include/JellyfinQt/dto/addvirtualfolderdto.h
	./include/JellyfinQt/dto/updatelibraryoptionsdto.h
	./include/JellyfinQt/dto/mediapathdto.h
	./include/JellyfinQt/dto/tunerchannelmapping.h
	./include/JellyfinQt/dto/nameidpair.h
	./include/JellyfinQt/dto/channelmappingoptionsdto.h
	./include/JellyfinQt/dto/setchannelmappingdto.h
	./include/JellyfinQt/dto/guideinfo.h
	./include/JellyfinQt/dto/livetvservicestatus.h
	./include/JellyfinQt/dto/livetvserviceinfo.h
	./include/JellyfinQt/dto/livetvinfo.h
	./include/JellyfinQt/dto/listingsproviderinfo.h
	./include/JellyfinQt/dto/getprogramsdto.h
	./include/JellyfinQt/dto/recordingstatus.h
	./include/JellyfinQt/dto/keepuntil.h
	./include/JellyfinQt/dto/daypattern.h
	./include/JellyfinQt/dto/seriestimerinfodto.h
	./include/JellyfinQt/dto/seriestimerinfodtoqueryresult.h
	./include/JellyfinQt/dto/timerinfodto.h
	./include/JellyfinQt/dto/timerinfodtoqueryresult.h
	./include/JellyfinQt/dto/tunerhostinfo.h
	./include/JellyfinQt/dto/localizationoption.h
	./include/JellyfinQt/dto/playbackerrorcode.h
	./include/JellyfinQt/dto/playbackinforesponse.h
	./include/JellyfinQt/dto/playbackinfodto.h
	./include/JellyfinQt/dto/openlivestreamdto.h
	./include/JellyfinQt/dto/livestreamresponse.h
	./include/JellyfinQt/dto/recommendationtype.h
	./include/JellyfinQt/dto/recommendationdto.h
	./include/JellyfinQt/dto/notificationlevel.h
	./include/JellyfinQt/dto/notificationdto.h
	./include/JellyfinQt/dto/notificationresultdto.h
	./include/JellyfinQt/dto/notificationssummarydto.h
	./include/JellyfinQt/dto/notificationtypeinfo.h
	./include/JellyfinQt/dto/versioninfo.h
	./include/JellyfinQt/dto/packageinfo.h
	./include/JellyfinQt/dto/createplaylistdto.h
	./include/JellyfinQt/dto/playlistcreationresult.h
	./include/JellyfinQt/dto/playmethod.h
	./include/JellyfinQt/dto/repeatmode.h
	./include/JellyfinQt/dto/queueitem.h
	./include/JellyfinQt/dto/playbackstartinfo.h
	./include/JellyfinQt/dto/playbackprogressinfo.h
	./include/JellyfinQt/dto/playbackstopinfo.h
	./include/JellyfinQt/dto/pluginstatus.h
	./include/JellyfinQt/dto/plugininfo.h
	./include/JellyfinQt/dto/basepluginconfiguration.h
	./include/JellyfinQt/dto/pluginsecurityinfo.h
	./include/JellyfinQt/dto/quickconnectstate.h
	./include/JellyfinQt/dto/quickconnectresult.h
	./include/JellyfinQt/dto/ratingtype.h
	./include/JellyfinQt/dto/remoteimageinfo.h
	./include/JellyfinQt/dto/remoteimageresult.h
	./include/JellyfinQt/dto/imageproviderinfo.h
	./include/JellyfinQt/dto/taskstate.h
	./include/JellyfinQt/dto/taskcompletionstatus.h
	./include/JellyfinQt/dto/taskresult.h
	./include/JellyfinQt/dto/tasktriggerinfo.h
	./include/JellyfinQt/dto/taskinfo.h
	./include/JellyfinQt/dto/searchhint.h
	./include/JellyfinQt/dto/searchhintresult.h
	./include/JellyfinQt/dto/playerstateinfo.h
	./include/JellyfinQt/dto/sessionuserinfo.h
	./include/JellyfinQt/dto/baseitem.h
	./include/JellyfinQt/dto/transcodereason.h
	./include/JellyfinQt/dto/transcodinginfo.h
	./include/JellyfinQt/dto/sessioninfo.h
	./include/JellyfinQt/dto/generalcommand.h
	./include/JellyfinQt/dto/playcommand.h
	./include/JellyfinQt/dto/playstatecommand.h
	./include/JellyfinQt/dto/clientcapabilitiesdto.h
	./include/JellyfinQt/dto/startupconfigurationdto.h
	./include/JellyfinQt/dto/startupuserdto.h
	./include/JellyfinQt/dto/startupremoteaccessdto.h
	./include/JellyfinQt/dto/fontfile.h
	./include/JellyfinQt/dto/remotesubtitleinfo.h
	./include/JellyfinQt/dto/uploadsubtitledto.h
	./include/JellyfinQt/dto/bufferrequestdto.h
	./include/JellyfinQt/dto/joingrouprequestdto.h
	./include/JellyfinQt/dto/groupstatetype.h
	./include/JellyfinQt/dto/groupinfodto.h
	./include/JellyfinQt/dto/moveplaylistitemrequestdto.h
	./include/JellyfinQt/dto/newgrouprequestdto.h
	./include/JellyfinQt/dto/nextitemrequestdto.h
	./include/JellyfinQt/dto/pingrequestdto.h
	./include/JellyfinQt/dto/previousitemrequestdto.h
	./include/JellyfinQt/dto/groupqueuemode.h
	./include/JellyfinQt/dto/queuerequestdto.h
	./include/JellyfinQt/dto/readyrequestdto.h
	./include/JellyfinQt/dto/removefromplaylistrequestdto.h
	./include/JellyfinQt/dto/seekrequestdto.h
	./include/JellyfinQt/dto/ignorewaitrequestdto.h
	./include/JellyfinQt/dto/playrequestdto.h
	./include/JellyfinQt/dto/setplaylistitemrequestdto.h
	./include/JellyfinQt/dto/grouprepeatmode.h
	./include/JellyfinQt/dto/setrepeatmoderequestdto.h
	./include/JellyfinQt/dto/groupshufflemode.h
	./include/JellyfinQt/dto/setshufflemoderequestdto.h
	./include/JellyfinQt/dto/endpointinfo.h
	./include/JellyfinQt/dto/installationinfo.h
	./include/JellyfinQt/dto/ffmpeglocation.h
	./include/JellyfinQt/dto/architecture.h
	./include/JellyfinQt/dto/systeminfo.h
	./include/JellyfinQt/dto/publicsysteminfo.h
	./include/JellyfinQt/dto/logfile.h
	./include/JellyfinQt/dto/wakeonlaninfo.h
	./include/JellyfinQt/dto/utctimeresponse.h
	./include/JellyfinQt/dto/subtitleplaybackmode.h
	./include/JellyfinQt/dto/userconfiguration.h
	./include/JellyfinQt/dto/dynamicdayofweek.h
	./include/JellyfinQt/dto/accessschedule.h
	./include/JellyfinQt/dto/unrateditem.h
	./include/JellyfinQt/dto/syncplayuseraccesstype.h
	./include/JellyfinQt/dto/userpolicy.h
	./include/JellyfinQt/dto/userdto.h
	./include/JellyfinQt/dto/authenticationresult.h
	./include/JellyfinQt/dto/updateusereasypassword.h
	./include/JellyfinQt/dto/updateuserpassword.h
	./include/JellyfinQt/dto/authenticateuserbyname.h
	./include/JellyfinQt/dto/quickconnectdto.h
	./include/JellyfinQt/dto/forgotpassworddto.h
	./include/JellyfinQt/dto/forgotpasswordaction.h
	./include/JellyfinQt/dto/forgotpasswordresult.h
	./include/JellyfinQt/dto/pinredeemresult.h
	./include/JellyfinQt/dto/createuserbyname.h
	./include/JellyfinQt/dto/specialviewoptiondto.h
	./include/JellyfinQt/dto/libraryupdateinfo.h
	./include/JellyfinQt/dto/iplugin.h
	./include/JellyfinQt/dto/playrequest.h
	./include/JellyfinQt/dto/playstaterequest.h
	./include/JellyfinQt/dto/timereventinfo.h
	./include/JellyfinQt/dto/sendcommandtype.h
	./include/JellyfinQt/dto/sendcommand.h
	./include/JellyfinQt/dto/groupupdatetype.h
	./include/JellyfinQt/dto/objectgroupupdate.h
	./include/JellyfinQt/loader/http/getlogentries.h
	./include/JellyfinQt/loader/http/getkeys.h
	./include/JellyfinQt/loader/http/createkey.h
	./include/JellyfinQt/loader/http/revokekey.h
	./include/JellyfinQt/loader/http/getartists.h
	./include/JellyfinQt/loader/http/getartistbyname.h
	./include/JellyfinQt/loader/http/getalbumartists.h
	./include/JellyfinQt/loader/http/getaudiostream.h
	./include/JellyfinQt/loader/http/headaudiostream.h
	./include/JellyfinQt/loader/http/getaudiostreambycontainer.h
	./include/JellyfinQt/loader/http/headaudiostreambycontainer.h
	./include/JellyfinQt/loader/http/getbrandingoptions.h
	./include/JellyfinQt/loader/http/getbrandingcss.h
	./include/JellyfinQt/loader/http/getbrandingcss_2.h
	./include/JellyfinQt/loader/http/getchannels.h
	./include/JellyfinQt/loader/http/getchannelfeatures.h
	./include/JellyfinQt/loader/http/getchannelitems.h
	./include/JellyfinQt/loader/http/getallchannelfeatures.h
	./include/JellyfinQt/loader/http/getlatestchannelitems.h
	./include/JellyfinQt/loader/http/createcollection.h
	./include/JellyfinQt/loader/http/addtocollection.h
	./include/JellyfinQt/loader/http/removefromcollection.h
	./include/JellyfinQt/loader/http/getconfiguration.h
	./include/JellyfinQt/loader/http/updateconfiguration.h
	./include/JellyfinQt/loader/http/getnamedconfiguration.h
	./include/JellyfinQt/loader/http/updatenamedconfiguration.h
	./include/JellyfinQt/loader/http/getdefaultmetadataoptions.h
	./include/JellyfinQt/loader/http/updatemediaencoderpath.h
	./include/JellyfinQt/loader/http/getdashboardconfigurationpage.h
	./include/JellyfinQt/loader/http/getconfigurationpages.h
	./include/JellyfinQt/loader/http/getdevices.h
	./include/JellyfinQt/loader/http/deletedevice.h
	./include/JellyfinQt/loader/http/getdeviceinfo.h
	./include/JellyfinQt/loader/http/getdeviceoptions.h
	./include/JellyfinQt/loader/http/updatedeviceoptions.h
	./include/JellyfinQt/loader/http/getdisplaypreferences.h
	./include/JellyfinQt/loader/http/updatedisplaypreferences.h
	./include/JellyfinQt/loader/http/getprofileinfos.h
	./include/JellyfinQt/loader/http/createprofile.h
	./include/JellyfinQt/loader/http/getprofile.h
	./include/JellyfinQt/loader/http/deleteprofile.h
	./include/JellyfinQt/loader/http/updateprofile.h
	./include/JellyfinQt/loader/http/getdefaultprofile.h
	./include/JellyfinQt/loader/http/getconnectionmanager.h
	./include/JellyfinQt/loader/http/getconnectionmanager_2.h
	./include/JellyfinQt/loader/http/getconnectionmanager_3.h
	./include/JellyfinQt/loader/http/processconnectionmanagercontrolrequest.h
	./include/JellyfinQt/loader/http/getcontentdirectory.h
	./include/JellyfinQt/loader/http/getcontentdirectory_2.h
	./include/JellyfinQt/loader/http/getcontentdirectory_3.h
	./include/JellyfinQt/loader/http/processcontentdirectorycontrolrequest.h
	./include/JellyfinQt/loader/http/getdescriptionxml.h
	./include/JellyfinQt/loader/http/getdescriptionxml_2.h
	./include/JellyfinQt/loader/http/geticonid.h
	./include/JellyfinQt/loader/http/getmediareceiverregistrar.h
	./include/JellyfinQt/loader/http/processmediareceiverregistrarcontrolrequest.h
	./include/JellyfinQt/loader/http/getmediareceiverregistrar_2.h
	./include/JellyfinQt/loader/http/getmediareceiverregistrar_3.h
	./include/JellyfinQt/loader/http/geticon.h
	./include/JellyfinQt/loader/http/gethlsaudiosegment.h
	./include/JellyfinQt/loader/http/getvarianthlsaudioplaylist.h
	./include/JellyfinQt/loader/http/getmasterhlsaudioplaylist.h
	./include/JellyfinQt/loader/http/headmasterhlsaudioplaylist.h
	./include/JellyfinQt/loader/http/gethlsvideosegment.h
	./include/JellyfinQt/loader/http/getvarianthlsvideoplaylist.h
	./include/JellyfinQt/loader/http/getmasterhlsvideoplaylist.h
	./include/JellyfinQt/loader/http/headmasterhlsvideoplaylist.h
	./include/JellyfinQt/loader/http/getdefaultdirectorybrowser.h
	./include/JellyfinQt/loader/http/getdirectorycontents.h
	./include/JellyfinQt/loader/http/getdrives.h
	./include/JellyfinQt/loader/http/getnetworkshares.h
	./include/JellyfinQt/loader/http/getparentpath.h
	./include/JellyfinQt/loader/http/validatepath.h
	./include/JellyfinQt/loader/http/getqueryfilterslegacy.h
	./include/JellyfinQt/loader/http/getqueryfilters.h
	./include/JellyfinQt/loader/http/getgenres.h
	./include/JellyfinQt/loader/http/getgenre.h
	./include/JellyfinQt/loader/http/gethlsaudiosegmentlegacyaac.h
	./include/JellyfinQt/loader/http/gethlsaudiosegmentlegacymp3.h
	./include/JellyfinQt/loader/http/gethlsvideosegmentlegacy.h
	./include/JellyfinQt/loader/http/gethlsplaylistlegacy.h
	./include/JellyfinQt/loader/http/stopencodingprocess.h
	./include/JellyfinQt/loader/http/getartistimage.h
	./include/JellyfinQt/loader/http/headartistimage.h
	./include/JellyfinQt/loader/http/getgenreimage.h
	./include/JellyfinQt/loader/http/headgenreimage.h
	./include/JellyfinQt/loader/http/getgenreimagebyindex.h
	./include/JellyfinQt/loader/http/headgenreimagebyindex.h
	./include/JellyfinQt/loader/http/getitemimageinfos.h
	./include/JellyfinQt/loader/http/deleteitemimage.h
	./include/JellyfinQt/loader/http/setitemimage.h
	./include/JellyfinQt/loader/http/getitemimage.h
	./include/JellyfinQt/loader/http/headitemimage.h
	./include/JellyfinQt/loader/http/deleteitemimagebyindex.h
	./include/JellyfinQt/loader/http/setitemimagebyindex.h
	./include/JellyfinQt/loader/http/getitemimagebyindex.h
	./include/JellyfinQt/loader/http/headitemimagebyindex.h
	./include/JellyfinQt/loader/http/getitemimage2.h
	./include/JellyfinQt/loader/http/headitemimage2.h
	./include/JellyfinQt/loader/http/updateitemimageindex.h
	./include/JellyfinQt/loader/http/getmusicgenreimage.h
	./include/JellyfinQt/loader/http/headmusicgenreimage.h
	./include/JellyfinQt/loader/http/getmusicgenreimagebyindex.h
	./include/JellyfinQt/loader/http/headmusicgenreimagebyindex.h
	./include/JellyfinQt/loader/http/getpersonimage.h
	./include/JellyfinQt/loader/http/headpersonimage.h
	./include/JellyfinQt/loader/http/getpersonimagebyindex.h
	./include/JellyfinQt/loader/http/headpersonimagebyindex.h
	./include/JellyfinQt/loader/http/getstudioimage.h
	./include/JellyfinQt/loader/http/headstudioimage.h
	./include/JellyfinQt/loader/http/getstudioimagebyindex.h
	./include/JellyfinQt/loader/http/headstudioimagebyindex.h
	./include/JellyfinQt/loader/http/postuserimage.h
	./include/JellyfinQt/loader/http/deleteuserimage.h
	./include/JellyfinQt/loader/http/getuserimage.h
	./include/JellyfinQt/loader/http/headuserimage.h
	./include/JellyfinQt/loader/http/getuserimagebyindex.h
	./include/JellyfinQt/loader/http/headuserimagebyindex.h
	./include/JellyfinQt/loader/http/postuserimagebyindex.h
	./include/JellyfinQt/loader/http/deleteuserimagebyindex.h
	./include/JellyfinQt/loader/http/getgeneralimages.h
	./include/JellyfinQt/loader/http/getgeneralimage.h
	./include/JellyfinQt/loader/http/getmediainfoimages.h
	./include/JellyfinQt/loader/http/getmediainfoimage.h
	./include/JellyfinQt/loader/http/getratingimages.h
	./include/JellyfinQt/loader/http/getratingimage.h
	./include/JellyfinQt/loader/http/getinstantmixfromalbum.h
	./include/JellyfinQt/loader/http/getinstantmixfromartists.h
	./include/JellyfinQt/loader/http/getinstantmixfromitem.h
	./include/JellyfinQt/loader/http/getinstantmixfrommusicgenres.h
	./include/JellyfinQt/loader/http/getinstantmixfrommusicgenre.h
	./include/JellyfinQt/loader/http/getinstantmixfromplaylist.h
	./include/JellyfinQt/loader/http/getinstantmixfromsong.h
	./include/JellyfinQt/loader/http/getexternalidinfos.h
	./include/JellyfinQt/loader/http/applysearchcriteria.h
	./include/JellyfinQt/loader/http/getbookremotesearchresults.h
	./include/JellyfinQt/loader/http/getboxsetremotesearchresults.h
	./include/JellyfinQt/loader/http/getremotesearchimage.h
	./include/JellyfinQt/loader/http/getmovieremotesearchresults.h
	./include/JellyfinQt/loader/http/getmusicalbumremotesearchresults.h
	./include/JellyfinQt/loader/http/getmusicartistremotesearchresults.h
	./include/JellyfinQt/loader/http/getmusicvideoremotesearchresults.h
	./include/JellyfinQt/loader/http/getpersonremotesearchresults.h
	./include/JellyfinQt/loader/http/getseriesremotesearchresults.h
	./include/JellyfinQt/loader/http/gettrailerremotesearchresults.h
	./include/JellyfinQt/loader/http/post.h
	./include/JellyfinQt/loader/http/getitems.h
	./include/JellyfinQt/loader/http/deleteitems.h
	./include/JellyfinQt/loader/http/getitemsbyuserid.h
	./include/JellyfinQt/loader/http/getresumeitems.h
	./include/JellyfinQt/loader/http/updateitem.h
	./include/JellyfinQt/loader/http/deleteitem.h
	./include/JellyfinQt/loader/http/updateitemcontenttype.h
	./include/JellyfinQt/loader/http/getmetadataeditorinfo.h
	./include/JellyfinQt/loader/http/getsimilaralbums.h
	./include/JellyfinQt/loader/http/getsimilarartists.h
	./include/JellyfinQt/loader/http/getancestors.h
	./include/JellyfinQt/loader/http/getcriticreviews.h
	./include/JellyfinQt/loader/http/getdownload.h
	./include/JellyfinQt/loader/http/getfile.h
	./include/JellyfinQt/loader/http/getsimilaritems.h
	./include/JellyfinQt/loader/http/getthememedia.h
	./include/JellyfinQt/loader/http/getthemesongs.h
	./include/JellyfinQt/loader/http/getthemevideos.h
	./include/JellyfinQt/loader/http/getitemcounts.h
	./include/JellyfinQt/loader/http/getlibraryoptionsinfo.h
	./include/JellyfinQt/loader/http/postupdatedmedia.h
	./include/JellyfinQt/loader/http/getmediafolders.h
	./include/JellyfinQt/loader/http/postaddedmovies.h
	./include/JellyfinQt/loader/http/postupdatedmovies.h
	./include/JellyfinQt/loader/http/getphysicalpaths.h
	./include/JellyfinQt/loader/http/refreshlibrary.h
	./include/JellyfinQt/loader/http/postaddedseries.h
	./include/JellyfinQt/loader/http/postupdatedseries.h
	./include/JellyfinQt/loader/http/getsimilarmovies.h
	./include/JellyfinQt/loader/http/getsimilarshows.h
	./include/JellyfinQt/loader/http/getsimilartrailers.h
	./include/JellyfinQt/loader/http/getvirtualfolders.h
	./include/JellyfinQt/loader/http/addvirtualfolder.h
	./include/JellyfinQt/loader/http/removevirtualfolder.h
	./include/JellyfinQt/loader/http/updatelibraryoptions.h
	./include/JellyfinQt/loader/http/renamevirtualfolder.h
	./include/JellyfinQt/loader/http/addmediapath.h
	./include/JellyfinQt/loader/http/removemediapath.h
	./include/JellyfinQt/loader/http/updatemediapath.h
	./include/JellyfinQt/loader/http/getchannelmappingoptions.h
	./include/JellyfinQt/loader/http/setchannelmapping.h
	./include/JellyfinQt/loader/http/getlivetvchannels.h
	./include/JellyfinQt/loader/http/getchannel.h
	./include/JellyfinQt/loader/http/getguideinfo.h
	./include/JellyfinQt/loader/http/getlivetvinfo.h
	./include/JellyfinQt/loader/http/addlistingprovider.h
	./include/JellyfinQt/loader/http/deletelistingprovider.h
	./include/JellyfinQt/loader/http/getdefaultlistingprovider.h
	./include/JellyfinQt/loader/http/getlineups.h
	./include/JellyfinQt/loader/http/getschedulesdirectcountries.h
	./include/JellyfinQt/loader/http/getliverecordingfile.h
	./include/JellyfinQt/loader/http/getlivestreamfile.h
	./include/JellyfinQt/loader/http/getlivetvprograms.h
	./include/JellyfinQt/loader/http/getprograms.h
	./include/JellyfinQt/loader/http/getprogram.h
	./include/JellyfinQt/loader/http/getrecommendedprograms.h
	./include/JellyfinQt/loader/http/getrecordings.h
	./include/JellyfinQt/loader/http/getrecording.h
	./include/JellyfinQt/loader/http/deleterecording.h
	./include/JellyfinQt/loader/http/getrecordingfolders.h
	./include/JellyfinQt/loader/http/getrecordinggroups.h
	./include/JellyfinQt/loader/http/getrecordinggroup.h
	./include/JellyfinQt/loader/http/getrecordingsseries.h
	./include/JellyfinQt/loader/http/getseriestimers.h
	./include/JellyfinQt/loader/http/createseriestimer.h
	./include/JellyfinQt/loader/http/getseriestimer.h
	./include/JellyfinQt/loader/http/cancelseriestimer.h
	./include/JellyfinQt/loader/http/updateseriestimer.h
	./include/JellyfinQt/loader/http/gettimers.h
	./include/JellyfinQt/loader/http/createtimer.h
	./include/JellyfinQt/loader/http/gettimer.h
	./include/JellyfinQt/loader/http/canceltimer.h
	./include/JellyfinQt/loader/http/updatetimer.h
	./include/JellyfinQt/loader/http/getdefaulttimer.h
	./include/JellyfinQt/loader/http/addtunerhost.h
	./include/JellyfinQt/loader/http/deletetunerhost.h
	./include/JellyfinQt/loader/http/gettunerhosttypes.h
	./include/JellyfinQt/loader/http/resettuner.h
	./include/JellyfinQt/loader/http/discovertuners.h
	./include/JellyfinQt/loader/http/discvovertuners.h
	./include/JellyfinQt/loader/http/getcountries.h
	./include/JellyfinQt/loader/http/getcultures.h
	./include/JellyfinQt/loader/http/getlocalizationoptions.h
	./include/JellyfinQt/loader/http/getparentalratings.h
	./include/JellyfinQt/loader/http/getplaybackinfo.h
	./include/JellyfinQt/loader/http/getpostedplaybackinfo.h
	./include/JellyfinQt/loader/http/closelivestream.h
	./include/JellyfinQt/loader/http/openlivestream.h
	./include/JellyfinQt/loader/http/getbitratetestbytes.h
	./include/JellyfinQt/loader/http/getmovierecommendations.h
	./include/JellyfinQt/loader/http/getmusicgenres.h
	./include/JellyfinQt/loader/http/getmusicgenre.h
	./include/JellyfinQt/loader/http/getnotifications.h
	./include/JellyfinQt/loader/http/setread.h
	./include/JellyfinQt/loader/http/getnotificationssummary.h
	./include/JellyfinQt/loader/http/setunread.h
	./include/JellyfinQt/loader/http/createadminnotification.h
	./include/JellyfinQt/loader/http/getnotificationservices.h
	./include/JellyfinQt/loader/http/getnotificationtypes.h
	./include/JellyfinQt/loader/http/getpackages.h
	./include/JellyfinQt/loader/http/getpackageinfo.h
	./include/JellyfinQt/loader/http/installpackage.h
	./include/JellyfinQt/loader/http/cancelpackageinstallation.h
	./include/JellyfinQt/loader/http/getrepositories.h
	./include/JellyfinQt/loader/http/setrepositories.h
	./include/JellyfinQt/loader/http/getpersons.h
	./include/JellyfinQt/loader/http/getperson.h
	./include/JellyfinQt/loader/http/createplaylist.h
	./include/JellyfinQt/loader/http/addtoplaylist.h
	./include/JellyfinQt/loader/http/removefromplaylist.h
	./include/JellyfinQt/loader/http/getplaylistitems.h
	./include/JellyfinQt/loader/http/moveitem.h
	./include/JellyfinQt/loader/http/reportplaybackstart.h
	./include/JellyfinQt/loader/http/pingplaybacksession.h
	./include/JellyfinQt/loader/http/reportplaybackprogress.h
	./include/JellyfinQt/loader/http/reportplaybackstopped.h
	./include/JellyfinQt/loader/http/markplayeditem.h
	./include/JellyfinQt/loader/http/markunplayeditem.h
	./include/JellyfinQt/loader/http/onplaybackstart.h
	./include/JellyfinQt/loader/http/onplaybackstopped.h
	./include/JellyfinQt/loader/http/onplaybackprogress.h
	./include/JellyfinQt/loader/http/getplugins.h
	./include/JellyfinQt/loader/http/uninstallplugin.h
	./include/JellyfinQt/loader/http/uninstallpluginbyversion.h
	./include/JellyfinQt/loader/http/disableplugin.h
	./include/JellyfinQt/loader/http/enableplugin.h
	./include/JellyfinQt/loader/http/getpluginimage.h
	./include/JellyfinQt/loader/http/getpluginconfiguration.h
	./include/JellyfinQt/loader/http/updatepluginconfiguration.h
	./include/JellyfinQt/loader/http/getpluginmanifest.h
	./include/JellyfinQt/loader/http/updatepluginsecurityinfo.h
	./include/JellyfinQt/loader/http/activate.h
	./include/JellyfinQt/loader/http/authorize.h
	./include/JellyfinQt/loader/http/available.h
	./include/JellyfinQt/loader/http/connect.h
	./include/JellyfinQt/loader/http/deauthorize.h
	./include/JellyfinQt/loader/http/initiate.h
	./include/JellyfinQt/loader/http/getstatus.h
	./include/JellyfinQt/loader/http/getremoteimage.h
	./include/JellyfinQt/loader/http/getremoteimages.h
	./include/JellyfinQt/loader/http/downloadremoteimage.h
	./include/JellyfinQt/loader/http/getremoteimageproviders.h
	./include/JellyfinQt/loader/http/gettasks.h
	./include/JellyfinQt/loader/http/gettask.h
	./include/JellyfinQt/loader/http/updatetask.h
	./include/JellyfinQt/loader/http/starttask.h
	./include/JellyfinQt/loader/http/stoptask.h
	./include/JellyfinQt/loader/http/get.h
	./include/JellyfinQt/loader/http/getpasswordresetproviders.h
	./include/JellyfinQt/loader/http/getauthproviders.h
	./include/JellyfinQt/loader/http/getsessions.h
	./include/JellyfinQt/loader/http/sendfullgeneralcommand.h
	./include/JellyfinQt/loader/http/sendgeneralcommand.h
	./include/JellyfinQt/loader/http/sendmessagecommand.h
	./include/JellyfinQt/loader/http/play.h
	./include/JellyfinQt/loader/http/sendplaystatecommand.h
	./include/JellyfinQt/loader/http/sendsystemcommand.h
	./include/JellyfinQt/loader/http/addusertosession.h
	./include/JellyfinQt/loader/http/removeuserfromsession.h
	./include/JellyfinQt/loader/http/displaycontent.h
	./include/JellyfinQt/loader/http/postcapabilities.h
	./include/JellyfinQt/loader/http/postfullcapabilities.h
	./include/JellyfinQt/loader/http/reportsessionended.h
	./include/JellyfinQt/loader/http/reportviewing.h
	./include/JellyfinQt/loader/http/completewizard.h
	./include/JellyfinQt/loader/http/getstartupconfiguration.h
	./include/JellyfinQt/loader/http/updateinitialconfiguration.h
	./include/JellyfinQt/loader/http/getfirstuser_2.h
	./include/JellyfinQt/loader/http/setremoteaccess.h
	./include/JellyfinQt/loader/http/getfirstuser.h
	./include/JellyfinQt/loader/http/updatestartupuser.h
	./include/JellyfinQt/loader/http/getstudios.h
	./include/JellyfinQt/loader/http/getstudio.h
	./include/JellyfinQt/loader/http/getfallbackfontlist.h
	./include/JellyfinQt/loader/http/getfallbackfont.h
	./include/JellyfinQt/loader/http/searchremotesubtitles.h
	./include/JellyfinQt/loader/http/downloadremotesubtitles.h
	./include/JellyfinQt/loader/http/getremotesubtitles.h
	./include/JellyfinQt/loader/http/getsubtitlewithticks.h
	./include/JellyfinQt/loader/http/getsubtitle.h
	./include/JellyfinQt/loader/http/getsubtitleplaylist.h
	./include/JellyfinQt/loader/http/uploadsubtitle.h
	./include/JellyfinQt/loader/http/deletesubtitle.h
	./include/JellyfinQt/loader/http/getsuggestions.h
	./include/JellyfinQt/loader/http/syncplaybuffering.h
	./include/JellyfinQt/loader/http/syncplayjoingroup.h
	./include/JellyfinQt/loader/http/syncplayleavegroup.h
	./include/JellyfinQt/loader/http/syncplaygetgroups.h
	./include/JellyfinQt/loader/http/syncplaymoveplaylistitem.h
	./include/JellyfinQt/loader/http/syncplaycreategroup.h
	./include/JellyfinQt/loader/http/syncplaynextitem.h
	./include/JellyfinQt/loader/http/syncplaypause.h
	./include/JellyfinQt/loader/http/syncplayping.h
	./include/JellyfinQt/loader/http/syncplaypreviousitem.h
	./include/JellyfinQt/loader/http/syncplayqueue.h
	./include/JellyfinQt/loader/http/syncplayready.h
	./include/JellyfinQt/loader/http/syncplayremovefromplaylist.h
	./include/JellyfinQt/loader/http/syncplayseek.h
	./include/JellyfinQt/loader/http/syncplaysetignorewait.h
	./include/JellyfinQt/loader/http/syncplaysetnewqueue.h
	./include/JellyfinQt/loader/http/syncplaysetplaylistitem.h
	./include/JellyfinQt/loader/http/syncplaysetrepeatmode.h
	./include/JellyfinQt/loader/http/syncplaysetshufflemode.h
	./include/JellyfinQt/loader/http/syncplaystop.h
	./include/JellyfinQt/loader/http/syncplayunpause.h
	./include/JellyfinQt/loader/http/getendpointinfo.h
	./include/JellyfinQt/loader/http/getsysteminfo.h
	./include/JellyfinQt/loader/http/getpublicsysteminfo.h
	./include/JellyfinQt/loader/http/getserverlogs.h
	./include/JellyfinQt/loader/http/getlogfile.h
	./include/JellyfinQt/loader/http/getpingsystem.h
	./include/JellyfinQt/loader/http/postpingsystem.h
	./include/JellyfinQt/loader/http/restartapplication.h
	./include/JellyfinQt/loader/http/shutdownapplication.h
	./include/JellyfinQt/loader/http/getwakeonlaninfo.h
	./include/JellyfinQt/loader/http/getutctime.h
	./include/JellyfinQt/loader/http/gettrailers.h
	./include/JellyfinQt/loader/http/getepisodes.h
	./include/JellyfinQt/loader/http/getseasons.h
	./include/JellyfinQt/loader/http/getnextup.h
	./include/JellyfinQt/loader/http/getupcomingepisodes.h
	./include/JellyfinQt/loader/http/getuniversalaudiostream.h
	./include/JellyfinQt/loader/http/headuniversalaudiostream.h
	./include/JellyfinQt/loader/http/getusers.h
	./include/JellyfinQt/loader/http/getuserbyid.h
	./include/JellyfinQt/loader/http/deleteuser.h
	./include/JellyfinQt/loader/http/updateuser.h
	./include/JellyfinQt/loader/http/authenticateuser.h
	./include/JellyfinQt/loader/http/updateuserconfiguration.h
	./include/JellyfinQt/loader/http/updateusereasypassword.h
	./include/JellyfinQt/loader/http/updateuserpassword.h
	./include/JellyfinQt/loader/http/updateuserpolicy.h
	./include/JellyfinQt/loader/http/authenticateuserbyname.h
	./include/JellyfinQt/loader/http/authenticatewithquickconnect.h
	./include/JellyfinQt/loader/http/forgotpassword.h
	./include/JellyfinQt/loader/http/forgotpasswordpin.h
	./include/JellyfinQt/loader/http/getcurrentuser.h
	./include/JellyfinQt/loader/http/createuserbyname.h
	./include/JellyfinQt/loader/http/getpublicusers.h
	./include/JellyfinQt/loader/http/markfavoriteitem.h
	./include/JellyfinQt/loader/http/unmarkfavoriteitem.h
	./include/JellyfinQt/loader/http/getitem.h
	./include/JellyfinQt/loader/http/getintros.h
	./include/JellyfinQt/loader/http/getlocaltrailers.h
	./include/JellyfinQt/loader/http/deleteuseritemrating.h
	./include/JellyfinQt/loader/http/updateuseritemrating.h
	./include/JellyfinQt/loader/http/getspecialfeatures.h
	./include/JellyfinQt/loader/http/getlatestmedia.h
	./include/JellyfinQt/loader/http/getrootfolder.h
	./include/JellyfinQt/loader/http/getgroupingoptions.h
	./include/JellyfinQt/loader/http/getuserviews.h
	./include/JellyfinQt/loader/http/getattachment.h
	./include/JellyfinQt/loader/http/getlivehlsstream.h
	./include/JellyfinQt/loader/http/getvideostreambycontainer.h
	./include/JellyfinQt/loader/http/headvideostreambycontainer.h
	./include/JellyfinQt/loader/http/getadditionalpart.h
	./include/JellyfinQt/loader/http/deletealternatesources.h
	./include/JellyfinQt/loader/http/getvideostream.h
	./include/JellyfinQt/loader/http/headvideostream.h
	./include/JellyfinQt/loader/http/mergeversions.h
	./include/JellyfinQt/loader/http/getyears.h
	./include/JellyfinQt/loader/http/getyear.h
	./include/JellyfinQt/loader/requesttypes.h)

set(openapi_SOURCES
	./src/dto/loglevel.cpp
	./src/dto/activitylogentry.cpp
	./src/dto/activitylogentryqueryresult.cpp
	./src/dto/authenticationinfo.cpp
	./src/dto/authenticationinfoqueryresult.cpp
	./src/dto/itemfields.cpp
	./src/dto/itemfilter.cpp
	./src/dto/imagetype.cpp
	./src/dto/video3dformat.cpp
	./src/dto/externalurl.cpp
	./src/dto/mediaprotocol.cpp
	./src/dto/mediasourcetype.cpp
	./src/dto/videotype.cpp
	./src/dto/isotype.cpp
	./src/dto/mediastreamtype.cpp
	./src/dto/subtitledeliverymethod.cpp
	./src/dto/mediastream.cpp
	./src/dto/mediaattachment.cpp
	./src/dto/transportstreamtimestamp.cpp
	./src/dto/mediasourceinfo.cpp
	./src/dto/playaccess.cpp
	./src/dto/mediaurl.cpp
	./src/dto/baseitemperson.cpp
	./src/dto/nameguidpair.cpp
	./src/dto/useritemdatadto.cpp
	./src/dto/dayofweek.cpp
	./src/dto/chapterinfo.cpp
	./src/dto/locationtype.cpp
	./src/dto/metadatafield.cpp
	./src/dto/imageorientation.cpp
	./src/dto/channeltype.cpp
	./src/dto/programaudio.cpp
	./src/dto/baseitemdto.cpp
	./src/dto/baseitemdtoqueryresult.cpp
	./src/dto/encodingcontext.cpp
	./src/dto/brandingoptions.cpp
	./src/dto/channelmediatype.cpp
	./src/dto/channelmediacontenttype.cpp
	./src/dto/channelitemsortfield.cpp
	./src/dto/channelfeatures.cpp
	./src/dto/collectioncreationresult.cpp
	./src/dto/version.cpp
	./src/dto/imagesavingconvention.cpp
	./src/dto/metadataoptions.cpp
	./src/dto/namevaluepair.cpp
	./src/dto/repositoryinfo.cpp
	./src/dto/pathsubstitution.cpp
	./src/dto/serverconfiguration.cpp
	./src/dto/mediaencoderpathdto.cpp
	./src/dto/problemdetails.cpp
	./src/dto/configurationpagetype.cpp
	./src/dto/configurationpageinfo.cpp
	./src/dto/generalcommandtype.cpp
	./src/dto/headermatchtype.cpp
	./src/dto/httpheaderinfo.cpp
	./src/dto/deviceidentification.cpp
	./src/dto/xmlattribute.cpp
	./src/dto/dlnaprofiletype.cpp
	./src/dto/directplayprofile.cpp
	./src/dto/transcodeseekinfo.cpp
	./src/dto/transcodingprofile.cpp
	./src/dto/profileconditiontype.cpp
	./src/dto/profileconditionvalue.cpp
	./src/dto/profilecondition.cpp
	./src/dto/containerprofile.cpp
	./src/dto/codectype.cpp
	./src/dto/codecprofile.cpp
	./src/dto/responseprofile.cpp
	./src/dto/subtitleprofile.cpp
	./src/dto/deviceprofile.cpp
	./src/dto/clientcapabilities.cpp
	./src/dto/deviceinfo.cpp
	./src/dto/deviceinfoqueryresult.cpp
	./src/dto/deviceoptions.cpp
	./src/dto/scrolldirection.cpp
	./src/dto/sortorder.cpp
	./src/dto/displaypreferencesdto.cpp
	./src/dto/deviceprofiletype.cpp
	./src/dto/deviceprofileinfo.cpp
	./src/dto/controlresponse.cpp
	./src/dto/defaultdirectorybrowserinfodto.cpp
	./src/dto/filesystementrytype.cpp
	./src/dto/filesystementryinfo.cpp
	./src/dto/validatepathdto.cpp
	./src/dto/queryfilterslegacy.cpp
	./src/dto/queryfilters.cpp
	./src/dto/imageformat.cpp
	./src/dto/imageinfo.cpp
	./src/dto/imagebynameinfo.cpp
	./src/dto/externalidmediatype.cpp
	./src/dto/externalidinfo.cpp
	./src/dto/remotesearchresult.cpp
	./src/dto/bookinfo.cpp
	./src/dto/bookinforemotesearchquery.cpp
	./src/dto/boxsetinfo.cpp
	./src/dto/boxsetinforemotesearchquery.cpp
	./src/dto/movieinfo.cpp
	./src/dto/movieinforemotesearchquery.cpp
	./src/dto/songinfo.cpp
	./src/dto/albuminfo.cpp
	./src/dto/albuminforemotesearchquery.cpp
	./src/dto/artistinfo.cpp
	./src/dto/artistinforemotesearchquery.cpp
	./src/dto/musicvideoinfo.cpp
	./src/dto/musicvideoinforemotesearchquery.cpp
	./src/dto/personlookupinfo.cpp
	./src/dto/personlookupinforemotesearchquery.cpp
	./src/dto/seriesinfo.cpp
	./src/dto/seriesinforemotesearchquery.cpp
	./src/dto/trailerinfo.cpp
	./src/dto/trailerinforemotesearchquery.cpp
	./src/dto/metadatarefreshmode.cpp
	./src/dto/seriesstatus.cpp
	./src/dto/parentalrating.cpp
	./src/dto/countryinfo.cpp
	./src/dto/culturedto.cpp
	./src/dto/metadataeditorinfo.cpp
	./src/dto/thememediaresult.cpp
	./src/dto/allthememediaresult.cpp
	./src/dto/itemcounts.cpp
	./src/dto/libraryoptioninfodto.cpp
	./src/dto/imageoption.cpp
	./src/dto/librarytypeoptionsdto.cpp
	./src/dto/libraryoptionsresultdto.cpp
	./src/dto/mediaupdateinfodto.cpp
	./src/dto/mediapathinfo.cpp
	./src/dto/typeoptions.cpp
	./src/dto/libraryoptions.cpp
	./src/dto/virtualfolderinfo.cpp
	./src/dto/addvirtualfolderdto.cpp
	./src/dto/updatelibraryoptionsdto.cpp
	./src/dto/mediapathdto.cpp
	./src/dto/tunerchannelmapping.cpp
	./src/dto/nameidpair.cpp
	./src/dto/channelmappingoptionsdto.cpp
	./src/dto/setchannelmappingdto.cpp
	./src/dto/guideinfo.cpp
	./src/dto/livetvservicestatus.cpp
	./src/dto/livetvserviceinfo.cpp
	./src/dto/livetvinfo.cpp
	./src/dto/listingsproviderinfo.cpp
	./src/dto/getprogramsdto.cpp
	./src/dto/recordingstatus.cpp
	./src/dto/keepuntil.cpp
	./src/dto/daypattern.cpp
	./src/dto/seriestimerinfodto.cpp
	./src/dto/seriestimerinfodtoqueryresult.cpp
	./src/dto/timerinfodto.cpp
	./src/dto/timerinfodtoqueryresult.cpp
	./src/dto/tunerhostinfo.cpp
	./src/dto/localizationoption.cpp
	./src/dto/playbackerrorcode.cpp
	./src/dto/playbackinforesponse.cpp
	./src/dto/playbackinfodto.cpp
	./src/dto/openlivestreamdto.cpp
	./src/dto/livestreamresponse.cpp
	./src/dto/recommendationtype.cpp
	./src/dto/recommendationdto.cpp
	./src/dto/notificationlevel.cpp
	./src/dto/notificationdto.cpp
	./src/dto/notificationresultdto.cpp
	./src/dto/notificationssummarydto.cpp
	./src/dto/notificationtypeinfo.cpp
	./src/dto/versioninfo.cpp
	./src/dto/packageinfo.cpp
	./src/dto/createplaylistdto.cpp
	./src/dto/playlistcreationresult.cpp
	./src/dto/playmethod.cpp
	./src/dto/repeatmode.cpp
	./src/dto/queueitem.cpp
	./src/dto/playbackstartinfo.cpp
	./src/dto/playbackprogressinfo.cpp
	./src/dto/playbackstopinfo.cpp
	./src/dto/pluginstatus.cpp
	./src/dto/plugininfo.cpp
	./src/dto/basepluginconfiguration.cpp
	./src/dto/pluginsecurityinfo.cpp
	./src/dto/quickconnectstate.cpp
	./src/dto/quickconnectresult.cpp
	./src/dto/ratingtype.cpp
	./src/dto/remoteimageinfo.cpp
	./src/dto/remoteimageresult.cpp
	./src/dto/imageproviderinfo.cpp
	./src/dto/taskstate.cpp
	./src/dto/taskcompletionstatus.cpp
	./src/dto/taskresult.cpp
	./src/dto/tasktriggerinfo.cpp
	./src/dto/taskinfo.cpp
	./src/dto/searchhint.cpp
	./src/dto/searchhintresult.cpp
	./src/dto/playerstateinfo.cpp
	./src/dto/sessionuserinfo.cpp
	./src/dto/baseitem.cpp
	./src/dto/transcodereason.cpp
	./src/dto/transcodinginfo.cpp
	./src/dto/sessioninfo.cpp
	./src/dto/generalcommand.cpp
	./src/dto/playcommand.cpp
	./src/dto/playstatecommand.cpp
	./src/dto/clientcapabilitiesdto.cpp
	./src/dto/startupconfigurationdto.cpp
	./src/dto/startupuserdto.cpp
	./src/dto/startupremoteaccessdto.cpp
	./src/dto/fontfile.cpp
	./src/dto/remotesubtitleinfo.cpp
	./src/dto/uploadsubtitledto.cpp
	./src/dto/bufferrequestdto.cpp
	./src/dto/joingrouprequestdto.cpp
	./src/dto/groupstatetype.cpp
	./src/dto/groupinfodto.cpp
	./src/dto/moveplaylistitemrequestdto.cpp
	./src/dto/newgrouprequestdto.cpp
	./src/dto/nextitemrequestdto.cpp
	./src/dto/pingrequestdto.cpp
	./src/dto/previousitemrequestdto.cpp
	./src/dto/groupqueuemode.cpp
	./src/dto/queuerequestdto.cpp
	./src/dto/readyrequestdto.cpp
	./src/dto/removefromplaylistrequestdto.cpp
	./src/dto/seekrequestdto.cpp
	./src/dto/ignorewaitrequestdto.cpp
	./src/dto/playrequestdto.cpp
	./src/dto/setplaylistitemrequestdto.cpp
	./src/dto/grouprepeatmode.cpp
	./src/dto/setrepeatmoderequestdto.cpp
	./src/dto/groupshufflemode.cpp
	./src/dto/setshufflemoderequestdto.cpp
	./src/dto/endpointinfo.cpp
	./src/dto/installationinfo.cpp
	./src/dto/ffmpeglocation.cpp
	./src/dto/architecture.cpp
	./src/dto/systeminfo.cpp
	./src/dto/publicsysteminfo.cpp
	./src/dto/logfile.cpp
	./src/dto/wakeonlaninfo.cpp
	./src/dto/utctimeresponse.cpp
	./src/dto/subtitleplaybackmode.cpp
	./src/dto/userconfiguration.cpp
	./src/dto/dynamicdayofweek.cpp
	./src/dto/accessschedule.cpp
	./src/dto/unrateditem.cpp
	./src/dto/syncplayuseraccesstype.cpp
	./src/dto/userpolicy.cpp
	./src/dto/userdto.cpp
	./src/dto/authenticationresult.cpp
	./src/dto/updateusereasypassword.cpp
	./src/dto/updateuserpassword.cpp
	./src/dto/authenticateuserbyname.cpp
	./src/dto/quickconnectdto.cpp
	./src/dto/forgotpassworddto.cpp
	./src/dto/forgotpasswordaction.cpp
	./src/dto/forgotpasswordresult.cpp
	./src/dto/pinredeemresult.cpp
	./src/dto/createuserbyname.cpp
	./src/dto/specialviewoptiondto.cpp
	./src/dto/libraryupdateinfo.cpp
	./src/dto/iplugin.cpp
	./src/dto/playrequest.cpp
	./src/dto/playstaterequest.cpp
	./src/dto/timereventinfo.cpp
	./src/dto/sendcommandtype.cpp
	./src/dto/sendcommand.cpp
	./src/dto/groupupdatetype.cpp
	./src/dto/objectgroupupdate.cpp
	./src/loader/http/getlogentries.cpp
	./src/loader/http/getkeys.cpp
	./src/loader/http/createkey.cpp
	./src/loader/http/revokekey.cpp
	./src/loader/http/getartists.cpp
	./src/loader/http/getartistbyname.cpp
	./src/loader/http/getalbumartists.cpp
	./src/loader/http/getaudiostream.cpp
	./src/loader/http/headaudiostream.cpp
	./src/loader/http/getaudiostreambycontainer.cpp
	./src/loader/http/headaudiostreambycontainer.cpp
	./src/loader/http/getbrandingoptions.cpp
	./src/loader/http/getbrandingcss.cpp
	./src/loader/http/getbrandingcss_2.cpp
	./src/loader/http/getchannels.cpp
	./src/loader/http/getchannelfeatures.cpp
	./src/loader/http/getchannelitems.cpp
	./src/loader/http/getallchannelfeatures.cpp
	./src/loader/http/getlatestchannelitems.cpp
	./src/loader/http/createcollection.cpp
	./src/loader/http/addtocollection.cpp
	./src/loader/http/removefromcollection.cpp
	./src/loader/http/getconfiguration.cpp
	./src/loader/http/updateconfiguration.cpp
	./src/loader/http/getnamedconfiguration.cpp
	./src/loader/http/updatenamedconfiguration.cpp
	./src/loader/http/getdefaultmetadataoptions.cpp
	./src/loader/http/updatemediaencoderpath.cpp
	./src/loader/http/getdashboardconfigurationpage.cpp
	./src/loader/http/getconfigurationpages.cpp
	./src/loader/http/getdevices.cpp
	./src/loader/http/deletedevice.cpp
	./src/loader/http/getdeviceinfo.cpp
	./src/loader/http/getdeviceoptions.cpp
	./src/loader/http/updatedeviceoptions.cpp
	./src/loader/http/getdisplaypreferences.cpp
	./src/loader/http/updatedisplaypreferences.cpp
	./src/loader/http/getprofileinfos.cpp
	./src/loader/http/createprofile.cpp
	./src/loader/http/getprofile.cpp
	./src/loader/http/deleteprofile.cpp
	./src/loader/http/updateprofile.cpp
	./src/loader/http/getdefaultprofile.cpp
	./src/loader/http/getconnectionmanager.cpp
	./src/loader/http/getconnectionmanager_2.cpp
	./src/loader/http/getconnectionmanager_3.cpp
	./src/loader/http/processconnectionmanagercontrolrequest.cpp
	./src/loader/http/getcontentdirectory.cpp
	./src/loader/http/getcontentdirectory_2.cpp
	./src/loader/http/getcontentdirectory_3.cpp
	./src/loader/http/processcontentdirectorycontrolrequest.cpp
	./src/loader/http/getdescriptionxml.cpp
	./src/loader/http/getdescriptionxml_2.cpp
	./src/loader/http/geticonid.cpp
	./src/loader/http/getmediareceiverregistrar.cpp
	./src/loader/http/processmediareceiverregistrarcontrolrequest.cpp
	./src/loader/http/getmediareceiverregistrar_2.cpp
	./src/loader/http/getmediareceiverregistrar_3.cpp
	./src/loader/http/geticon.cpp
	./src/loader/http/gethlsaudiosegment.cpp
	./src/loader/http/getvarianthlsaudioplaylist.cpp
	./src/loader/http/getmasterhlsaudioplaylist.cpp
	./src/loader/http/headmasterhlsaudioplaylist.cpp
	./src/loader/http/gethlsvideosegment.cpp
	./src/loader/http/getvarianthlsvideoplaylist.cpp
	./src/loader/http/getmasterhlsvideoplaylist.cpp
	./src/loader/http/headmasterhlsvideoplaylist.cpp
	./src/loader/http/getdefaultdirectorybrowser.cpp
	./src/loader/http/getdirectorycontents.cpp
	./src/loader/http/getdrives.cpp
	./src/loader/http/getnetworkshares.cpp
	./src/loader/http/getparentpath.cpp
	./src/loader/http/validatepath.cpp
	./src/loader/http/getqueryfilterslegacy.cpp
	./src/loader/http/getqueryfilters.cpp
	./src/loader/http/getgenres.cpp
	./src/loader/http/getgenre.cpp
	./src/loader/http/gethlsaudiosegmentlegacyaac.cpp
	./src/loader/http/gethlsaudiosegmentlegacymp3.cpp
	./src/loader/http/gethlsvideosegmentlegacy.cpp
	./src/loader/http/gethlsplaylistlegacy.cpp
	./src/loader/http/stopencodingprocess.cpp
	./src/loader/http/getartistimage.cpp
	./src/loader/http/headartistimage.cpp
	./src/loader/http/getgenreimage.cpp
	./src/loader/http/headgenreimage.cpp
	./src/loader/http/getgenreimagebyindex.cpp
	./src/loader/http/headgenreimagebyindex.cpp
	./src/loader/http/getitemimageinfos.cpp
	./src/loader/http/deleteitemimage.cpp
	./src/loader/http/setitemimage.cpp
	./src/loader/http/getitemimage.cpp
	./src/loader/http/headitemimage.cpp
	./src/loader/http/deleteitemimagebyindex.cpp
	./src/loader/http/setitemimagebyindex.cpp
	./src/loader/http/getitemimagebyindex.cpp
	./src/loader/http/headitemimagebyindex.cpp
	./src/loader/http/getitemimage2.cpp
	./src/loader/http/headitemimage2.cpp
	./src/loader/http/updateitemimageindex.cpp
	./src/loader/http/getmusicgenreimage.cpp
	./src/loader/http/headmusicgenreimage.cpp
	./src/loader/http/getmusicgenreimagebyindex.cpp
	./src/loader/http/headmusicgenreimagebyindex.cpp
	./src/loader/http/getpersonimage.cpp
	./src/loader/http/headpersonimage.cpp
	./src/loader/http/getpersonimagebyindex.cpp
	./src/loader/http/headpersonimagebyindex.cpp
	./src/loader/http/getstudioimage.cpp
	./src/loader/http/headstudioimage.cpp
	./src/loader/http/getstudioimagebyindex.cpp
	./src/loader/http/headstudioimagebyindex.cpp
	./src/loader/http/postuserimage.cpp
	./src/loader/http/deleteuserimage.cpp
	./src/loader/http/getuserimage.cpp
	./src/loader/http/headuserimage.cpp
	./src/loader/http/getuserimagebyindex.cpp
	./src/loader/http/headuserimagebyindex.cpp
	./src/loader/http/postuserimagebyindex.cpp
	./src/loader/http/deleteuserimagebyindex.cpp
	./src/loader/http/getgeneralimages.cpp
	./src/loader/http/getgeneralimage.cpp
	./src/loader/http/getmediainfoimages.cpp
	./src/loader/http/getmediainfoimage.cpp
	./src/loader/http/getratingimages.cpp
	./src/loader/http/getratingimage.cpp
	./src/loader/http/getinstantmixfromalbum.cpp
	./src/loader/http/getinstantmixfromartists.cpp
	./src/loader/http/getinstantmixfromitem.cpp
	./src/loader/http/getinstantmixfrommusicgenres.cpp
	./src/loader/http/getinstantmixfrommusicgenre.cpp
	./src/loader/http/getinstantmixfromplaylist.cpp
	./src/loader/http/getinstantmixfromsong.cpp
	./src/loader/http/getexternalidinfos.cpp
	./src/loader/http/applysearchcriteria.cpp
	./src/loader/http/getbookremotesearchresults.cpp
	./src/loader/http/getboxsetremotesearchresults.cpp
	./src/loader/http/getremotesearchimage.cpp
	./src/loader/http/getmovieremotesearchresults.cpp
	./src/loader/http/getmusicalbumremotesearchresults.cpp
	./src/loader/http/getmusicartistremotesearchresults.cpp
	./src/loader/http/getmusicvideoremotesearchresults.cpp
	./src/loader/http/getpersonremotesearchresults.cpp
	./src/loader/http/getseriesremotesearchresults.cpp
	./src/loader/http/gettrailerremotesearchresults.cpp
	./src/loader/http/post.cpp
	./src/loader/http/getitems.cpp
	./src/loader/http/deleteitems.cpp
	./src/loader/http/getitemsbyuserid.cpp
	./src/loader/http/getresumeitems.cpp
	./src/loader/http/updateitem.cpp
	./src/loader/http/deleteitem.cpp
	./src/loader/http/updateitemcontenttype.cpp
	./src/loader/http/getmetadataeditorinfo.cpp
	./src/loader/http/getsimilaralbums.cpp
	./src/loader/http/getsimilarartists.cpp
	./src/loader/http/getancestors.cpp
	./src/loader/http/getcriticreviews.cpp
	./src/loader/http/getdownload.cpp
	./src/loader/http/getfile.cpp
	./src/loader/http/getsimilaritems.cpp
	./src/loader/http/getthememedia.cpp
	./src/loader/http/getthemesongs.cpp
	./src/loader/http/getthemevideos.cpp
	./src/loader/http/getitemcounts.cpp
	./src/loader/http/getlibraryoptionsinfo.cpp
	./src/loader/http/postupdatedmedia.cpp
	./src/loader/http/getmediafolders.cpp
	./src/loader/http/postaddedmovies.cpp
	./src/loader/http/postupdatedmovies.cpp
	./src/loader/http/getphysicalpaths.cpp
	./src/loader/http/refreshlibrary.cpp
	./src/loader/http/postaddedseries.cpp
	./src/loader/http/postupdatedseries.cpp
	./src/loader/http/getsimilarmovies.cpp
	./src/loader/http/getsimilarshows.cpp
	./src/loader/http/getsimilartrailers.cpp
	./src/loader/http/getvirtualfolders.cpp
	./src/loader/http/addvirtualfolder.cpp
	./src/loader/http/removevirtualfolder.cpp
	./src/loader/http/updatelibraryoptions.cpp
	./src/loader/http/renamevirtualfolder.cpp
	./src/loader/http/addmediapath.cpp
	./src/loader/http/removemediapath.cpp
	./src/loader/http/updatemediapath.cpp
	./src/loader/http/getchannelmappingoptions.cpp
	./src/loader/http/setchannelmapping.cpp
	./src/loader/http/getlivetvchannels.cpp
	./src/loader/http/getchannel.cpp
	./src/loader/http/getguideinfo.cpp
	./src/loader/http/getlivetvinfo.cpp
	./src/loader/http/addlistingprovider.cpp
	./src/loader/http/deletelistingprovider.cpp
	./src/loader/http/getdefaultlistingprovider.cpp
	./src/loader/http/getlineups.cpp
	./src/loader/http/getschedulesdirectcountries.cpp
	./src/loader/http/getliverecordingfile.cpp
	./src/loader/http/getlivestreamfile.cpp
	./src/loader/http/getlivetvprograms.cpp
	./src/loader/http/getprograms.cpp
	./src/loader/http/getprogram.cpp
	./src/loader/http/getrecommendedprograms.cpp
	./src/loader/http/getrecordings.cpp
	./src/loader/http/getrecording.cpp
	./src/loader/http/deleterecording.cpp
	./src/loader/http/getrecordingfolders.cpp
	./src/loader/http/getrecordinggroups.cpp
	./src/loader/http/getrecordinggroup.cpp
	./src/loader/http/getrecordingsseries.cpp
	./src/loader/http/getseriestimers.cpp
	./src/loader/http/createseriestimer.cpp
	./src/loader/http/getseriestimer.cpp
	./src/loader/http/cancelseriestimer.cpp
	./src/loader/http/updateseriestimer.cpp
	./src/loader/http/gettimers.cpp
	./src/loader/http/createtimer.cpp
	./src/loader/http/gettimer.cpp
	./src/loader/http/canceltimer.cpp
	./src/loader/http/updatetimer.cpp
	./src/loader/http/getdefaulttimer.cpp
	./src/loader/http/addtunerhost.cpp
	./src/loader/http/deletetunerhost.cpp
	./src/loader/http/gettunerhosttypes.cpp
	./src/loader/http/resettuner.cpp
	./src/loader/http/discovertuners.cpp
	./src/loader/http/discvovertuners.cpp
	./src/loader/http/getcountries.cpp
	./src/loader/http/getcultures.cpp
	./src/loader/http/getlocalizationoptions.cpp
	./src/loader/http/getparentalratings.cpp
	./src/loader/http/getplaybackinfo.cpp
	./src/loader/http/getpostedplaybackinfo.cpp
	./src/loader/http/closelivestream.cpp
	./src/loader/http/openlivestream.cpp
	./src/loader/http/getbitratetestbytes.cpp
	./src/loader/http/getmovierecommendations.cpp
	./src/loader/http/getmusicgenres.cpp
	./src/loader/http/getmusicgenre.cpp
	./src/loader/http/getnotifications.cpp
	./src/loader/http/setread.cpp
	./src/loader/http/getnotificationssummary.cpp
	./src/loader/http/setunread.cpp
	./src/loader/http/createadminnotification.cpp
	./src/loader/http/getnotificationservices.cpp
	./src/loader/http/getnotificationtypes.cpp
	./src/loader/http/getpackages.cpp
	./src/loader/http/getpackageinfo.cpp
	./src/loader/http/installpackage.cpp
	./src/loader/http/cancelpackageinstallation.cpp
	./src/loader/http/getrepositories.cpp
	./src/loader/http/setrepositories.cpp
	./src/loader/http/getpersons.cpp
	./src/loader/http/getperson.cpp
	./src/loader/http/createplaylist.cpp
	./src/loader/http/addtoplaylist.cpp
	./src/loader/http/removefromplaylist.cpp
	./src/loader/http/getplaylistitems.cpp
	./src/loader/http/moveitem.cpp
	./src/loader/http/reportplaybackstart.cpp
	./src/loader/http/pingplaybacksession.cpp
	./src/loader/http/reportplaybackprogress.cpp
	./src/loader/http/reportplaybackstopped.cpp
	./src/loader/http/markplayeditem.cpp
	./src/loader/http/markunplayeditem.cpp
	./src/loader/http/onplaybackstart.cpp
	./src/loader/http/onplaybackstopped.cpp
	./src/loader/http/onplaybackprogress.cpp
	./src/loader/http/getplugins.cpp
	./src/loader/http/uninstallplugin.cpp
	./src/loader/http/uninstallpluginbyversion.cpp
	./src/loader/http/disableplugin.cpp
	./src/loader/http/enableplugin.cpp
	./src/loader/http/getpluginimage.cpp
	./src/loader/http/getpluginconfiguration.cpp
	./src/loader/http/updatepluginconfiguration.cpp
	./src/loader/http/getpluginmanifest.cpp
	./src/loader/http/updatepluginsecurityinfo.cpp
	./src/loader/http/activate.cpp
	./src/loader/http/authorize.cpp
	./src/loader/http/available.cpp
	./src/loader/http/connect.cpp
	./src/loader/http/deauthorize.cpp
	./src/loader/http/initiate.cpp
	./src/loader/http/getstatus.cpp
	./src/loader/http/getremoteimage.cpp
	./src/loader/http/getremoteimages.cpp
	./src/loader/http/downloadremoteimage.cpp
	./src/loader/http/getremoteimageproviders.cpp
	./src/loader/http/gettasks.cpp
	./src/loader/http/gettask.cpp
	./src/loader/http/updatetask.cpp
	./src/loader/http/starttask.cpp
	./src/loader/http/stoptask.cpp
	./src/loader/http/get.cpp
	./src/loader/http/getpasswordresetproviders.cpp
	./src/loader/http/getauthproviders.cpp
	./src/loader/http/getsessions.cpp
	./src/loader/http/sendfullgeneralcommand.cpp
	./src/loader/http/sendgeneralcommand.cpp
	./src/loader/http/sendmessagecommand.cpp
	./src/loader/http/play.cpp
	./src/loader/http/sendplaystatecommand.cpp
	./src/loader/http/sendsystemcommand.cpp
	./src/loader/http/addusertosession.cpp
	./src/loader/http/removeuserfromsession.cpp
	./src/loader/http/displaycontent.cpp
	./src/loader/http/postcapabilities.cpp
	./src/loader/http/postfullcapabilities.cpp
	./src/loader/http/reportsessionended.cpp
	./src/loader/http/reportviewing.cpp
	./src/loader/http/completewizard.cpp
	./src/loader/http/getstartupconfiguration.cpp
	./src/loader/http/updateinitialconfiguration.cpp
	./src/loader/http/getfirstuser_2.cpp
	./src/loader/http/setremoteaccess.cpp
	./src/loader/http/getfirstuser.cpp
	./src/loader/http/updatestartupuser.cpp
	./src/loader/http/getstudios.cpp
	./src/loader/http/getstudio.cpp
	./src/loader/http/getfallbackfontlist.cpp
	./src/loader/http/getfallbackfont.cpp
	./src/loader/http/searchremotesubtitles.cpp
	./src/loader/http/downloadremotesubtitles.cpp
	./src/loader/http/getremotesubtitles.cpp
	./src/loader/http/getsubtitlewithticks.cpp
	./src/loader/http/getsubtitle.cpp
	./src/loader/http/getsubtitleplaylist.cpp
	./src/loader/http/uploadsubtitle.cpp
	./src/loader/http/deletesubtitle.cpp
	./src/loader/http/getsuggestions.cpp
	./src/loader/http/syncplaybuffering.cpp
	./src/loader/http/syncplayjoingroup.cpp
	./src/loader/http/syncplayleavegroup.cpp
	./src/loader/http/syncplaygetgroups.cpp
	./src/loader/http/syncplaymoveplaylistitem.cpp
	./src/loader/http/syncplaycreategroup.cpp
	./src/loader/http/syncplaynextitem.cpp
	./src/loader/http/syncplaypause.cpp
	./src/loader/http/syncplayping.cpp
	./src/loader/http/syncplaypreviousitem.cpp
	./src/loader/http/syncplayqueue.cpp
	./src/loader/http/syncplayready.cpp
	./src/loader/http/syncplayremovefromplaylist.cpp
	./src/loader/http/syncplayseek.cpp
	./src/loader/http/syncplaysetignorewait.cpp
	./src/loader/http/syncplaysetnewqueue.cpp
	./src/loader/http/syncplaysetplaylistitem.cpp
	./src/loader/http/syncplaysetrepeatmode.cpp
	./src/loader/http/syncplaysetshufflemode.cpp
	./src/loader/http/syncplaystop.cpp
	./src/loader/http/syncplayunpause.cpp
	./src/loader/http/getendpointinfo.cpp
	./src/loader/http/getsysteminfo.cpp
	./src/loader/http/getpublicsysteminfo.cpp
	./src/loader/http/getserverlogs.cpp
	./src/loader/http/getlogfile.cpp
	./src/loader/http/getpingsystem.cpp
	./src/loader/http/postpingsystem.cpp
	./src/loader/http/restartapplication.cpp
	./src/loader/http/shutdownapplication.cpp
	./src/loader/http/getwakeonlaninfo.cpp
	./src/loader/http/getutctime.cpp
	./src/loader/http/gettrailers.cpp
	./src/loader/http/getepisodes.cpp
	./src/loader/http/getseasons.cpp
	./src/loader/http/getnextup.cpp
	./src/loader/http/getupcomingepisodes.cpp
	./src/loader/http/getuniversalaudiostream.cpp
	./src/loader/http/headuniversalaudiostream.cpp
	./src/loader/http/getusers.cpp
	./src/loader/http/getuserbyid.cpp
	./src/loader/http/deleteuser.cpp
	./src/loader/http/updateuser.cpp
	./src/loader/http/authenticateuser.cpp
	./src/loader/http/updateuserconfiguration.cpp
	./src/loader/http/updateusereasypassword.cpp
	./src/loader/http/updateuserpassword.cpp
	./src/loader/http/updateuserpolicy.cpp
	./src/loader/http/authenticateuserbyname.cpp
	./src/loader/http/authenticatewithquickconnect.cpp
	./src/loader/http/forgotpassword.cpp
	./src/loader/http/forgotpasswordpin.cpp
	./src/loader/http/getcurrentuser.cpp
	./src/loader/http/createuserbyname.cpp
	./src/loader/http/getpublicusers.cpp
	./src/loader/http/markfavoriteitem.cpp
	./src/loader/http/unmarkfavoriteitem.cpp
	./src/loader/http/getitem.cpp
	./src/loader/http/getintros.cpp
	./src/loader/http/getlocaltrailers.cpp
	./src/loader/http/deleteuseritemrating.cpp
	./src/loader/http/updateuseritemrating.cpp
	./src/loader/http/getspecialfeatures.cpp
	./src/loader/http/getlatestmedia.cpp
	./src/loader/http/getrootfolder.cpp
	./src/loader/http/getgroupingoptions.cpp
	./src/loader/http/getuserviews.cpp
	./src/loader/http/getattachment.cpp
	./src/loader/http/getlivehlsstream.cpp
	./src/loader/http/getvideostreambycontainer.cpp
	./src/loader/http/headvideostreambycontainer.cpp
	./src/loader/http/getadditionalpart.cpp
	./src/loader/http/deletealternatesources.cpp
	./src/loader/http/getvideostream.cpp
	./src/loader/http/headvideostream.cpp
	./src/loader/http/mergeversions.cpp
	./src/loader/http/getyears.cpp
	./src/loader/http/getyear.cpp
	./src/loader/requesttypes.cpp)
