name: doxygen
run-name: Generate and deploy Doxygen documentation
on: 
  push:
    branches:
      - "master"
  workflow_dispatch: {}
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure pages
        uses: actions/configure-pages@v3
      - name: Install the doxyqml filter
        run: pip install doxyqml
      - name: Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.5
      - name: Upload GitHub pages artifact
        uses: "actions/upload-pages-artifact@v2"
        with:
          path: "doxygen/html/"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: "actions/deploy-pages@v2"
